[project]
name = "heron"
version = "0.1.0"
description = "Revived an Old Project Back"
readme = "README.md"
authors = [
    { name = "bitwise-rude", email = "080bel042.meyan@pcampus.edu.np" }
]
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "ddgs>=9.16.0",
    "fbchat-muqit>=1.2.2",
    "giphy-client>=1.0.0",
    "gtts>=2.2.4",
    "nepali-datetime>=1.0.8.5",
    "pillow>=12.3.0",
    "pytube>=15.0.0",
    "requests>=2.34.2",
    "wikipedia-api>=0.16.0",
    "yt-dlp>=2026.8.19",
]

[project.scripts]
heron = "heron:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

