[project]
name = "heron"
version = "0.1.0"
description = "Revived an Old Project Back"
readme = "README.md"
authors = [
    { name = "bitwise-rude", email = "080bel042.meyan@pcampus.edu.np" }
]
requires-python = ">=3.13"
dependencies = [
    "fbchat-muqit>=1.2.2",
    "nepali-datetime>=1.0.8.5",
    "pillow>=12.3.0",
    "requests>=2.34.2",
]

[project.scripts]
heron = "heron:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

